baseURL = "/"
languageCode = "bg"
title = "Белот Уики"
themesDir = "themes"
theme = "hugo-whisper-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "Начало"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Уики"
    url = "/docs/"
    weight = 2

[params]
  google_analytics_id = ""
  homepage_button_link = '/docs'
  homepage_button_text = 'Към Съдържанието'
  homepage_intro = 'Whisper is a documentation theme built with Hugo. The design and functionality is intentionally minimal.'
  homepage_image = '/images/terminal.gif'

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "Белот Уики съдържа информация и често задавани въпроси за играта Белот."
    meta_og_title = "Белот Уики"
    meta_og_type = "website"
    meta_og_url = "https://hugo-whisper.netlify.app" # TODO
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-whisper-theme/master/images/tn.png"
    meta_og_description = "Hugo Whisper is a documentation theme built with Hugo."
    meta_twitter_card = "summary"
    meta_twitter_site = "@_middlehut_"
    meta_twitter_creator = "@_middlehut_"

  [params.logo]
      mobile = "/images/logo-mobile.svg"
      standard  = "/images/logo.svg"
